### ISSUE TITLE
How to train DiffBIR for face retouching?

### ISSUE THREAD

**Issue by luser350** [XPixelGroup/DiffBIR#113]
Hi, thanks for sharing your awesome work. I want to train DiffBIR on 1024 x1024 [ffhqr dataset](https://github.com/skylab-tech/ffhqr-dataset). I want to use [ffhq dataset](https://github.com/NVlabs/ffhq-dataset/tree/master) as input (1024x024).
 I have modified [codeformer](https://github.com/XPixelGroup/DiffBIR/blob/main/dataset/codeformer.py) __getitem__().
```python
def __getitem__(self, index: int) -> Dict[str, Union[np.ndarray, str]]:
        # load gt image
        img_gt = None
        while img_gt is None:
            # load meta file
            image_file = self.image_files[index]
            gt_path = image_file["image_path"]
            prompt = image_file["prompt"]
            img_gt = self.load_gt_image(gt_path)
            if img_gt is None:
                print(f"filed to load {gt_path}, try another image")
                index = random.randint(0, len(self) - 1)
        
        # Shape: (h, w, c); channel order: BGR; image range: [0, 1], float32.
        img_gt = (img_gt[..., ::-1] / 255.0).astype(np.float32)
        h, w, _ = img_gt.shape
        if np.random.uniform() < 0.5:
            prompt = ""
        
        # ------------------------ generate lq image ------------------------ #
        lq_path = gt_path.replace("ffhqr", "ffhq")
        img_lq = cv2.imread(lq_path)
        img_lq = img_lq.astype(np.float32)/255.0
        
        # BGR to RGB, [-1, 1]
        gt = (img_gt[..., ::-1] * 2 - 1).astype(np.float32)
        # BGR to RGB, [0, 1]
        lq = img_lq[..., ::-1].astype(np.float32)
        
        return gt, lq, prompt
```
I have generated the training.list and validation.list for ffhqr.
Please guide:
1. Which pre-trained model I should use, the face_swinir_v1.ckpt or v1_face.pth.
2. Does I need to train stage_1 or I can directly train stage_2
3. I want input 1024x1024 and output 1024x1024

**Comment by luser350** [comment]
@chxy95 @hejingwenhejingwen @xinntao @WenlongZhang0517 can somebody answer my question, please?

**Comment by luser350** [comment]
Hi, thanks for replying. Please tell me which VAE you are referring to. Please guide me on how to verify the VAE.

**Comment by luser350** [comment]
Hi I have completed the above step. Here is my script
```python
from model.cldm import ControlLDM
from utils.common import instantiate_from_config
from omegaconf import OmegaConf
import torch
import torchvision.transforms as transforms
from PIL import Image

# Define the transformation
transform = transforms.Compose([
    transforms.ToTensor(), 
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]) 
])

cldm: ControlLDM = instantiate_from_config(OmegaConf.load("configs/inference/cldm.yaml"))
# VAE is contained in pretrained SD
sd = torch.load("pretrained/v2-1_512-ema-pruned.ckpt", map_location="cpu")
#unused = cldm.load_pretrained_sd(sd)
#print(f"strictly load pretrained sd_v2.1, unused weights: {unused}")
cldm.eval().to("cpu")

# load image and convert to tensor
img = Image.open("00006.png").convert("RGB")
x = transform(img)
x = x.unsqueeze(0)
#x = x.permute(0, 2, 3, 1)

with torch.no_grad():
    z = cldm.vae_encode(x)
    x_decoded = cldm.vae_decode(z)

# reverse normalization
x_decoded = x_decoded.squeeze()#.permute(1, 2, 0) 
x_decoded = (x_decoded * 0.5) + 0.5 
img_decoded = (transforms.ToPILImage()(x_decoded.cpu().clamp(0, 1)))

img_decoded.save("decoded_image.png")
```
I have commented out these two lines
```python
unused = cldm.load_pretrained_sd(sd)
print(f"strictly load pretrained sd_v2.1, unused weights: {unused}")
```
It was giving a KeyError
```python
Traceback (most recent call last):
  File "/home/danial/Desktop/diffbir/DiffBIR/vae.py", line 16, in <module>
    unused = cldm.load_pretrained_sd(sd)
  File "/home/danial/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/danial/Desktop/diffbir/DiffBIR/model/cldm.py", line 51, in load_pretrained_sd
    init_sd[key] = sd[target_key].clone()
KeyError: 'model.diffusion_model.time_embed.0.weight'
```
My input image
![00006](https://github.com/XPixelGroup/DiffBIR/assets/168648774/dc2ef532-3ab9-44ad-94ff-b9c3662fcf27)
Decoded Image
![decoded_image](https://github.com/XPixelGroup/DiffBIR/assets/168648774/dccc124f-9b03-4c97-97e0-c76c747a46bf)

So the decoder has failed?
