### ISSUE TITLE
failed finding central directory

### ISSUE THREAD

**Issue by MyraBaba** [XPixelGroup/DiffBIR#56]
for general image inference

/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "/home/bc/Projects/OpenSource/DiffBIR/inference.py", line 216, in <module>
    main()
  File "/home/bc/Projects/OpenSource/DiffBIR/inference.py", line 141, in main
    load_state_dict(model, torch.load(args.ckpt, map_location="cpu"), strict=True)
  File "/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by MyraBaba** [comment]
any update @chxy95 

Loading model from: /home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "/home/bc/Projects/OpenSource/DiffBIR/inference_face.py", line 261, in <module>
    main()
  File "/home/bc/Projects/OpenSource/DiffBIR/inference_face.py", line 133, in main
    bg_upsampler = build_diffbir_model(args.config, 'weights/general_full_v1.pth')
  File "/home/bc/Projects/OpenSource/DiffBIR/inference_face.py", line 100, in build_diffbir_model
    load_state_dict(model, torch.load(ckpt), strict=True)
  File "/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/bc/Projects/OpenSource/DiffBIR/venvDiffBIR/lib/python3.10/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by AIchemist369** [comment]
Hello, I also encountered the same problem as you during the reproduction process. I kept trying to solve the problem but still couldn't solve it. Please tell me, has your problem been solved so far?

**Comment by JFrankLee** [comment]
I have the same problem, too.
