### ISSUE TITLE
not support  apple m1

### ISSUE THREAD

**Issue by fever365** [XPixelGroup/DiffBIR#8]
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    max(query.shape[-1] != value.shape[-1]) > 128
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    max(query.shape[-1] != value.shape[-1]) > 128
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512

**Comment by 0x3f3f3f3fun** [comment]
xformers doesn't support apple m1: https://github.com/facebookresearch/xformers/issues/775.

**Comment by 0x3f3f3f3fun** [comment]
We will add support for the Apple M1, but it may take some time because we currently do not have Apple M1 for debugging😢. We will upload some demo in the next few days, such as the Hugging Face demo, so you can try them out in the meantime. 😄Thanks for your interest on DiffBIR!

**Comment by c4fun** [comment]
Thanks for the reply. I've downloaded the new code and bump into the following questions. These are merely some suggestions as they may or may not solve the problem.

## 1. cudatoolkit not support in Apple M1
### Original command
```bash
conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch
conda install xformers==0.0.16 -c xformers
```

### New command suggestion
Remove the cudatoolkit
```
conda install pytorch==1.12.1 torchvision==0.13.1 -c pytorch
```
## 2. requirements.txt fix
As `triton` not supported on m1 mac, the `triton` should not be included in `requirements.txt` and should be installed by other ways if needed.

```
Collecting pytorch_lightning==1.4.2 (from -r requirements.txt (line 1))
  Using cached pytorch_lightning-1.4.2-py3-none-any.whl (916 kB)
Requirement already satisfied: einops in /opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.6.1)
Collecting open-clip-torch (from -r requirements.txt (line 3))
  Obtaining dependency information for open-clip-torch from https://files.pythonhosted.org/packages/70/b9/a9f2c37f998c20be57fed0128934f4a311c6596c1f6b9c2fe358b26125bc/open_clip_torch-2.20.0-py3-none-any.whl.metadata
  Using cached open_clip_torch-2.20.0-py3-none-any.whl.metadata (46 kB)
Collecting omegaconf (from -r requirements.txt (line 4))
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting torchmetrics==0.6.0 (from -r requirements.txt (line 5))
  Using cached torchmetrics-0.6.0-py3-none-any.whl (329 kB)
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
```

## 3. quickstart fix

### Original command
```bash
python gradio_diffbir.py \
--ckpt weights/general_full_v1.ckpt \
--config configs/model/cldm.yaml \
--reload_swinir \
--swinir_ckpt weights/general_swinir_v1.ckpt \
--device cuda
```

### New command exploration
1. perhaps we need to remove the `device` parameter? I'm running without it but bumps into this problem:

```
Traceback (most recent call last):
  File "/Users/xxx/code/github.com/XPixelGroup/DiffBIR/gradio_diffbir.py", line 40, in <module>
    model.to(args.device)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
    return super().to(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/cuda/__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
zsh: command not found: --device
```

2. Then it occurs to me that cpu is also a device, hence this command
```
python gradio_diffbir.py \
--ckpt weights/general_full_v1.ckpt \
--config configs/model/cldm.yaml \
--reload_swinir \
--swinir_ckpt weights/general_swinir_v1.ckpt \
--device cpu
```

But it occurs there's problem with the gradio. So I've added `share=True` in gradio_diffbir.py and it seems to be working.


```
No module 'xformers'. Proceeding without it.
DISABLE XFORMERS!
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
reload swinir model from weights/general_swinir_v1.ckpt
/Users/xxx/code/github.com/XPixelGroup/DiffBIR/gradio_diffbir.py:157: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  result_gallery = gr.Gallery(label="Output", show_label=False, elem_id="gallery").style(grid=2, height="auto")
/Users/xxx/code/github.com/XPixelGroup/DiffBIR/gradio_diffbir.py:157: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  result_gallery = gr.Gallery(label="Output", show_label=False, elem_id="gallery").style(grid=2, height="auto")
Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "/Users/xxx/code/github.com/XPixelGroup/DiffBIR/gradio_diffbir.py", line 175, in <module>
    block.launch(server_name='0.0.0.0')
  File "/opt/homebrew/anaconda3/envs/diffbir/lib/python3.10/site-packages/gradio/blocks.py", line 1982, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

3. Hope the `--device mps` will be supported. Currently it is not supported. But I see a lot of other frameworks support this option.

> @fever365 @c4fun Hey guys, we have discovered that this issue is not related to Apple M1. The root cause is that our code doesn't support CPU inference. Our code defaults to using xformers for inference, and xformers doesn't support CPU, which is why our code doesn't work on CPU. We have now fixed this issue, please pull the latest updates to get it to work correctly. We hope you can successfully run our model on Apple M1. If you have any further questions, please feel free to reach out to us anytime!

**Comment by ikehat** [comment]
I have a max-spec MacStudio (128 GB ram) I can make available. Contact me at ikehat@gmail.com

**Comment by ziyannchen** [comment]
@c4fun @ikehat Hey, I've tried to deploy on my M1 Mac laptop and it runs successfully on CPU.
Please check this [xOS Installation](https://github.com/XPixelGroup/DiffBIR/blob/main/assets/docs/installation_xOS.md) to set up.
We're still working on MPS device support and please stay tuned for the progress.

**Comment by ziyannchen** [comment]
Hey guys, we just added support for Apple Silicon to inference on CPU/MPS devices. Check the updates and have a try!
