### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted?   which file ?

### ISSUE THREAD

**Issue by laowalter** [XPixelGroup/DiffBIR#95]
HI, all

According https://github.com/XPixelGroup/DiffBIR/issues/45,

I have added version: "${HOME}/.cache/huggingface/hub/open_clip_pytorch_model.bin"  to configs/model/cldm.yaml,
downloaded alexnet-owl-7be5be79.pth to  ~/.cache/torch/hub/checkpoints/,  open_clip_pytorch_model.bin to ~/.cache/huggingface/hub/.

Running "  python gradio_diffbir.py --ckpt weights/general_full_v1.ckpt --config configs/model/cldm.yaml --reload_swinir --swinir_ckpt weights/general_swinir_v1.ckpt --device cuda" got following error

....
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
/home/quant/.virtualenvs/diffbir/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/quant/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/quant/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in thefuture. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/q/myapps/DiffBIR/gradio_diffbir.py", line 32, in <module>
    model: ControlLDM = instantiate_from_config(OmegaConf.load(args.config))
  File "/home/q/myapps/DiffBIR/utils/common.py", line 18, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/q/myapps/DiffBIR/model/cldm.py", line 309, in __init__
    self.preprocess_model = instantiate_from_config(preprocess_config)
  File "/home/q/myapps/DiffBIR/ldm/util.py", line 80, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/q/myapps/DiffBIR/model/swinir.py", line 825, in __init__
    self.lpips_metric = LPIPS(net="alex")
  File "/home/q/myapps/DiffBIR/utils/metrics.py", line 44, in __init__
    self.model = lpips.LPIPS(net=net)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/lpips/lpips.py", line 84, in __init__
    self.net = net_type(pretrained=not self.pnet_rand, requires_grad=self.pnet_tune)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/lpips/pretrained_networks.py", line 59,in __init__
    alexnet_pretrained_features = tv.alexnet(pretrained=pretrained).features
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/alexnet.py", line 115, in alexnet
    model.load_state_dict(weights.get_state_dict(progress=progress))
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torchvision/models/_api.py", line 66, in get_state_dict
    return load_state_dict_from_url(self.url, progress=progress)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torch/hub.py", line 735, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/q/.virtualenvs/diffbir/lib/python3.10/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

Thanks for any advice.

**Comment by laowalter** [comment]
Solved! alexnet-owt-7be5be79.pth is corrupted.
